GRANT ALL ON SCHEMA public TO public ;
CREATE TABLE users(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email varchar(255) UNIQUE NOT NULL,
    password_hash varchar(255)  NOT NULL,
    first_name VARCHAR(64) not null,
    last_name varchar(64) not null ,
    role varchar(20) not null default 'ROLE_USER',
    created_at timestamptz default CURRENT_TIMESTAMP
);